# Generated by Django 4.2.8 on 2023-12-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mecanica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
