# Generated by Django 4.2.8 on 2023-12-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mecanica', '0006_alter_equipe_membros_alter_equipe_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(to='app_mecanica.mecanico'),
        ),
    ]
