# Generated by Django 4.2.8 on 2023-12-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mecanica', '0007_alter_equipe_membros'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemdeservico',
            name='problema',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peca',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
