# Generated by Django 4.2.8 on 2023-12-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mecanica', '0008_ordemdeservico_problema_peca_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemdeservico',
            name='problema',
        ),
        migrations.RemoveField(
            model_name='peca',
            name='quantidade',
        ),
    ]
