# Generated by Django 4.2.8 on 2023-12-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mecanica', '0004_alter_servico_ordem_de_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='mecanico',
        ),
        migrations.AddField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(to='app_mecanica.mecanico'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
