# Generated by Django 4.2.8 on 2023-12-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mecanica', '0005_remove_equipe_mecanico_equipe_membros_equipe_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='membros',
            field=models.ManyToManyField(related_name='equipes', to='app_mecanica.mecanico'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
